### PR TITLE
Fix login and signup errors

### LINKED ISSUE #275: Login and signup errors are still being misdirected
There are four places for potential errors to display: the sign in box on the home page, the sign up box on the home page, and the sign up and sign in pages. Almost all of the errors on these pages are either not showing, or not showing in the right spot. Let's fix.

https://stefanbauer.me/tips-and-tricks/multiple-forms-with-same-input-names-on-one-page

### PR DESCRIPTION
**Pull request by tomdiggle**
This commit fixes #275 the errors on the sign up, login and home page. It uses a seperate FormRequest for Login and Register each with a custom loginForm and registerForm ErrorBag.

### CODE REVIEW

File: tests/AccountTest.php [hunk 1]
```diff
@@ -34,10 +34,7 @@ function invalid_signups_dont_proceed()
     {
         $this->visit('register')
             ->press('Sign up')
-            ->seePageIs('register')
-            ->see('The name field is required')
-            ->see('The password field is required')
-            ->see('The email field is required');
+            ->seePageIs('register');
```
Comment (mattstauffer) [inline tests/AccountTest.php]: Are we no longer seeing those errors?

File: app/Http/Controllers/Auth/LoginController.php [hunk 2]
```diff
@@ -41,4 +37,37 @@ public function __construct()
     {
         $this->middleware('guest', ['except' => 'logout']);
     }
+
```
Comment (mattstauffer) [inline app/Http/Controllers/Auth/LoginController.php]: Any time I take a method and reproduce it purely to change its syntax, I like to A) pass through as much of the functionality up to its parent as I can, and B) note that it's 98% (or whatever) the same as its parent so that, in the future, someone knows why we have all this complexity here that aren't in most apps. E.g. "This is almost the exact same method as Illuminate\Whatever\LoginControllerTraitOrWhatever@login, just modified to accept a form request" (or whatever.)

Same note for the register method on the RegisterController.

Comment (tomdiggle) [reply app/Http/Controllers/Auth/LoginController.php]: I agree. I've just changed to extend the parent methods and pass a RegisterFormRequest and LoginFormRequest. Hope this solves this issue.

File: tests/AccountTest.php (hunk 1 above)
Comment (tomdiggle) [reply tests/AccountTest.php]: Ah, yes we do see those errors. I've re-added them and also the errors are now displayed below the text inputs.

Screenshot 2019-09-04 at 21 15 53

File: app/Http/Controllers/Auth/LoginController.php (hunk 2 above)
Comment (mattstauffer) [reply app/Http/Controllers/Auth/LoginController.php]: Brilliant--thanks!

**Comment by mattstauffer** [comment]
Thanks so much @tomdiggle!
